import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { Command } from "commander";
import yaml from "js-yaml";
import type { ArrayReq, CheckNode, FieldReq } from "../core/check.js";
import { RULE_REGISTRY, type RuleMeta } from "../core/rule.js";

// ── Public command ────────────────────────────────────────────────────────────

export function cmdExportRegistry(): Command {
  return new Command("export-registry")
    .description("Export obligation and assertion registries as YAML from rule definitions")
    .option("--output <dir>", "Output directory", "registry")
    .option("--framework <fw>", "Limit to one framework (e.g. eu-ai-act)")
    .action(async (opts: { output: string; framework?: string }) => {
      await import("../frameworks/euAiAct/index.js");
      await import("../frameworks/iso42001/index.js");

      let rules = [...RULE_REGISTRY];
      if (opts.framework) rules = rules.filter((r) => r.framework === opts.framework);

      const byFramework = groupBy(rules, (r) => r.framework);

      for (const [fw, fwRules] of Object.entries(byFramework)) {
        const dir = join(opts.output, fw);
        mkdirSync(dir, { recursive: true });

        const assertionsOut = serializeAssertions(fwRules);
        const obligationsOut = serializeObligations(fwRules);

        writeFileSync(join(dir, "assertions.yaml"), assertionsOut, "utf-8");
        writeFileSync(join(dir, "obligations.yaml"), obligationsOut, "utf-8");

        console.log(`  ${fw}/assertions.yaml    (${fwRules.length} assertions)`);
        const oblCount = new Set(fwRules.map((r) => r.obligation).filter(Boolean)).size;
        console.log(`  ${fw}/obligations.yaml   (${oblCount} obligations)`);
      }

      console.log(`\nExported to ${opts.output}/`);
      console.log("These files are generated — do not edit manually.");
      console.log("Regenerate with: rulestatus export-registry");
    });
}

// ── Assertions ────────────────────────────────────────────────────────────────

function serializeAssertions(rules: RuleMeta[]): string {
  const header = [
    "# Assertion registry — generated by: rulestatus export-registry",
    "# Do not edit manually. Source of truth: src/frameworks/*/article*.ts",
    "# Regenerate: rulestatus export-registry",
    "",
  ].join("\n");

  const assertions = rules.map((r) => ({
    id: r.id,
    obligationId: r.obligation ?? null,
    article: r.article,
    title: r.title,
    severity: r.severity,
    appliesTo: r.appliesTo,
    legalText: r.legalText ?? null,
    remediation: r.remediation ?? null,
    check: r.check ? serializeCheckNode(r.check) : { type: "imperative-fn" },
    reviewStatus: "not-reviewed",
  }));

  return header + yaml.dump({ assertions }, { lineWidth: 120, noRefs: true });
}

// ── Obligations ───────────────────────────────────────────────────────────────

function serializeObligations(rules: RuleMeta[]): string {
  const header = [
    "# Obligation registry — generated by: rulestatus export-registry",
    "# Do not edit manually. Source of truth: src/frameworks/*/article*.ts",
    "# Regenerate: rulestatus export-registry",
    "",
  ].join("\n");

  // Deduplicate by obligationId — use first rule's metadata per obligation
  const seen = new Map<string, RuleMeta>();
  for (const r of rules) {
    if (r.obligation && !seen.has(r.obligation)) seen.set(r.obligation, r);
  }

  const obligations = [...seen.entries()].map(([oblId, r]) => ({
    id: oblId,
    article: r.article,
    title: r.title,
    legalText: r.legalText ?? null,
    appliesTo: r.appliesTo,
    assertionIds: rules.filter((x) => x.obligation === oblId).map((x) => x.id),
    reviewStatus: "not-reviewed",
  }));

  return header + yaml.dump({ obligations }, { lineWidth: 120, noRefs: true });
}

// ── CheckNode serializer ──────────────────────────────────────────────────────

function serializeCheckNode(node: CheckNode): Record<string, unknown> {
  switch (node.kind) {
    case "doc":
      return {
        type: "document",
        category: node.category,
        searchPaths: node.paths,
        acceptedFormats: node.fmts,
        ...(node.reqs.length > 0 ? { requiredFields: node.reqs.map(serializeFieldReq) } : {}),
        ...(node.minCoverage
          ? {
              minFieldCoverage: {
                threshold: node.minCoverage.threshold,
                fields: node.minCoverage.fields,
              },
            }
          : {}),
      };

    case "structured":
      return {
        type: "structured-file",
        name: node.name,
        ...(node.reqs.length > 0 ? { requiredFields: node.reqs.map(serializeFieldReq) } : {}),
        ...(node.arrayReqs.length > 0
          ? { arrayChecks: node.arrayReqs.map(serializeArrayReq) }
          : {}),
      };

    case "config":
      return {
        type: "config",
        name: node.name,
        ...(node.reqs.length > 0 ? { requiredFields: node.reqs.map(serializeFieldReq) } : {}),
        ...(node.valueChecks.length > 0 ? { nestedValueChecks: node.valueChecks } : {}),
        ...(node.valueInChecks.length > 0
          ? {
              valueInChecks: node.valueInChecks.map((v) => ({
                fields: v.fields,
                validValues: [...v.values],
              })),
            }
          : {}),
      };

    case "model-card":
      return {
        type: "model-card",
        ...(node.reqs.length > 0 ? { requiredFields: node.reqs.map(serializeFieldReq) } : {}),
      };

    case "api":
      return {
        type: "api",
        endpoint: node.endpoint,
        ...(node.requireOk ? { requireOk: true } : {}),
        ...(node.excludeStatus !== undefined ? { excludeStatus: node.excludeStatus } : {}),
      };

    case "system-field":
      return {
        type: "system-field",
        field: node.field,
        ...(node.values ? { validValues: [...node.values] } : {}),
      };

    case "manual":
      return { type: "manual", reason: node.reason };

    case "any-of":
      return { type: "any-of", checks: node.checks.map(serializeCheckNode) };
  }
}

function serializeFieldReq(r: FieldReq): Record<string, unknown> {
  if (r.field) {
    return {
      field: r.field,
      ...(r.withinMonths !== undefined ? { withinMonths: r.withinMonths } : {}),
    };
  }
  return {
    anyOf: r.anyOf,
    ...(r.withinMonths !== undefined ? { withinMonths: r.withinMonths } : {}),
  };
}

function serializeArrayReq(r: ArrayReq): Record<string, unknown> {
  return {
    field: r.field,
    ...(r.minLength !== undefined ? { minLength: r.minLength } : {}),
    ...(r.coversDimensions ? { coversDimensions: r.coversDimensions } : {}),
    ...(r.hasAnyEntry ? { hasAnyEntry: r.hasAnyEntry } : {}),
    ...(r.coversAtLeast
      ? { coversAtLeast: { n: r.coversAtLeast.n, fromList: [...r.coversAtLeast.fromList] } }
      : {}),
  };
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function groupBy<T>(arr: T[], key: (item: T) => string): Record<string, T[]> {
  const result: Record<string, T[]> = {};
  for (const item of arr) {
    const k = key(item);
    if (!result[k]) result[k] = [];
    result[k].push(item);
  }
  return result;
}
